#!/bin/sh

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

set -e

if [[ "$(which xcpretty)" == "" ]]
then
    echo "Installing xcpretty."
    sudo gem install xcpretty
fi

if [[ ! -e .bin/rt ]]
then
    echo "Rebuilding release tools."
    pushd Dependencies/ReleaseTools > /dev/null
    swift run builder build --configuration release
    cp .build/release/rt ../../.bin/rt
    popd > /dev/null
fi

echo "Using release tools $(rt --version)."
