#!/bin/sh

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

# This script builds the rt command line tool into `.build/tools/rt`,
# so that other scripts or build phases can find it.
# If the --rebuild flag is passed, it will force a rebuild, and then run
# `rt bootstrap` to update the rt scripts (including this one) to their
# latest versions.
#
# Note that this script is set up to work as a SPM command plugin, but 
# running it that way is currently unreliable.
#
# Instead it is recommended that you:
# - copy this script into the client project
# - run it once to bootstrap the tools
# - run the `upload` script to upload your app to testflight / the app store

HOMEBREW_NO_AUTO_UPDATE=true
brew install xcbeautify --quiet

REBUILD=false
if [[ "$1" == "--rebuild" ]]
then
    echo "Forced rebuild of release tools."
    REBUILD=true
fi

set -euo pipefail  # (add an x to flags to enable debugging)

LOCALTOOLS="$PWD/../ReleaseTools"
if [[ -e "$LOCALTOOLS" ]]
then
    RT="$LOCALTOOLS/.build/debug/rt"
else
    TOOLS="$PWD/.build/tools"
    TOOLSRC="$TOOLS/src"
    RTSRC="$TOOLSRC/ReleaseTools"
    RT="$RTSRC/.build/debug/rt"
fi


if $REBUILD || [ ! -f "$RT" ]
then
    if [[ -e "$LOCALTOOLS" ]]
    then
        echo "Updating local release tools."
        pushd "$LOCALTOOLS" > /dev/null
    else
        if [[ ! -e "$RTSRC" ]]
        then
            echo "Cloning release tools."
            mkdir -p "$TOOLSRC"
            pushd "$TOOLSRC" > /dev/null
            git clone git@github.com:elegantchaos/ReleaseTools.git
            cd "$RTSRC"
        else
            pushd "$RTSRC" > /dev/null
            git fetch
            git checkout main
            git pull
        fi
        echo "Updating release tools."
    fi

    swift run rt --version
    popd > /dev/null
    "$RT" bootstrap
fi

RTV=`"$RT" --version`
echo "Using release tools $RTV."

